# Rust sample hello world application crate.

[package]
name = "rust_hello"
version = "0.1.0"
edition = "2024"
description = """
Rust NUSA hello world application.
"""
license = "MIT"

[dependencies.nusa]
version = "0.1.0"
path = "../../rust/nusa"

[dependencies.log]
version = "0.4.27"
